version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install git
          command: 'apt-get update && sudo apt-get install -y git'
      - run:
          name: Create folder structure mirroring development
          command: 'bash /root/project/.circleci/setup_directory.sh'
      - run:
          name: Checkout googletest
          command: 'git clone https://github.com/google/googletest.git /root/tools/googletest/'
      - run:
          name: Build googletest
          command: 'cd /root/tools/googletest/googletest && cmake . && make'
      - run:
          name: Build googlemock
          command: 'cd /root/tools/googletest/googlemock && cmake . && make'
      - run:
          name: Build all the project things
          command: 'cd /root/courses/beginning-cpp/ && cmake . && make'
      - run:
          name: Run random integer utility tests
          command: '/root/courses/beginning-cpp/utils/random_integer/test/random_integer_test'
      - run:
          name: Run section6-challenge tests
          command: '/root/courses/beginning-cpp/section6-challenge/test/test_estimation_tool'
