version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Checkout googletest
          command: git clone https://github.com/google/googletest.git && pwd
      - run:
          name: Build all the project things
          command: 'cmake . && make'
      - run:
          name: Run utils/random_integer tests
          command: './utils/random_integer/test/random_integer_test'
